### ISSUE TITLE
Missing file in repository

### ISSUE THREAD

**Issue by pbathuk** [prahjister/Calibration-Generator#1]
I am trying to build from source & have found that the command:
`pyrcc5 -o RetCalResource_rc.py RetCalResource.qrc`

returns with 
`Cannot find file: Retract Modelsm.jpg`

From looking through the file I can see that on L4: 
https://github.com/prahjister/Calibration-Generator/blob/ca963aeeae3f9bc4d47aa7b97de6905f03be30ae/RetCalResource.qrc#L4

it references this file, but does not have it in the repository to utilise.
I am going to try to remove it & if successful will submit a PR for you.

**Comment by prahjister** [comment]
Where you able to compile properly after this? And what platform are you compiling on?
